version: '3'

services:
  myapp:
    image: myapp-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./model.pkl:/code/model.pkl
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
